### ISSUE TITLE
Two questions about save track_detection result to npy file.

### ISSUE THREAD

**Issue by Senwang98** [olly-styles/Multiple-Object-Forecasting#11]
Hi, olly
By the way, i still have two questions about saving npy.

Q1: Velocity calculate?
For t-29 ~ t frames, we just only save t-24 ~ t? 
In fame t-24, velocity_x is calculate by (x[25] - x[29]) / 4 or (x[24] - x[29] ) / 5?

Q2: Save order?
Assuming that the current frame is t, what is the order in which you save frames t-24~t? My approach is to find a frame (labeled = 1), read a total of 30 frames from t-29 to t, t-24 is the first frame that needs to be saved, and save it until t in chronological order. I wonder if there is a problem with my approach?
My save order is just like this: t-24, t-23.....t(just in time order)

**Comment by olly-styles** [comment]
Q1: Yes, just t-24 to t.  The velocity is computed using 5 frames, so (x[24] - x[29] ) / 5
Q2: Yes, that's the same approach I used.

**Comment by Senwang98** [comment]
Great! 
After i have saved optical flow pictures, the next thing is to use DTP to save dtp_feature. The previous frames and future frames setteing are different between DTP and MOF, is anything i need to change to make DTP meets MOF's need? 
By the way, why dtp_feature's size is 2048?
Thanks again.

**Comment by olly-styles** [comment]
I'm not sure what you mean by "The previous frames and future frames setteing are different between DTP and MOF", could you elaborate?

A feature size of 2048 was chosen as any other hyperparameter would be, using cross-validation.

**Comment by Senwang98** [comment]
Sorry i didn't describe it clearly.
Because DTP and MOF are not exactly the same, so I need to make some modifications to the hyperparameters. Specifically, which parameters should I modify? For example, the number of past and predicted frames, the output of resnet18, etc.(modify the input and output to be 30 and 60, then retrain the DTP?)

For dtp_feature size which size is 2048, i stiil feel confused about it since the CNN's output is 30.
