### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by StephenEkaputra** [olly-styles/Multiple-Object-Forecasting#15]
Hi, Olly

I tried to train custom dataset with DTP repository https://github.com/olly-styles/Dynamic-Trajectory-Predictor
I have some questions about it:
1. Which one is the optical flow features result? Which one is the bounding boxes features result?
2. How to output like Citywalks dataset numpy files with the size of 3-dimension and with 3-fold dataset (e.g., 169341,8,25)?

Thank you.

**Comment by olly-styles** [comment]
Hi Stephen,

1. DTP uses optical flow features only for trajectory prediction. Therefore, there are no bounding box features for DTP.
2. The format of this is (data_sample, bounding box, timestep). The bounding box has 8 dimensions as we also include the velocity, as described in Section 5.1 of the paper and also this post: https://github.com/olly-styles/Multiple-Object-Forecasting/issues/9

Hope I've understood your questions and answered them. Please let me know if not.
