### ISSUE TITLE
The bounding box size exceeds the image size

### ISSUE THREAD

**Issue by hunterace832100** [olly-styles/Multiple-Object-Forecasting#16]
Hi,olly

I like your project very much. During my own implementation, I found a problem, that is, your target detection frame is not processed after being obtained by YOLOv3, which will cause the actual size of some detection bounding box  to exceed the size of the image.

I see that you directly use these bounding boxes that exceed the image size in dtp_box_statistics.npy and dtp_targets.npy. How do you explain this? And how did you crop the target area later?

**Comment by olly-styles** [comment]
Hi, happy to hear you're finding our work useful.

We clip detections that exceed the frame area. e.g.., if a bounding box coordinate is -5, it would be considered as 0

**Comment by hunterace832100** [comment]
Okay, thank you,

That means dtp_box_statistics.npy uses bounding boxes that have not been processed directly. 

After reading your article about DTP and MOF, there is a problem that bothers me. The output of STED is a vector of (delta_velocity_x, delta_velocity_y, delta_w, delta_h). So how does your dtp_target.npy file calculate these four target values? 

I calculate here according to the method mentioned in the article (v_t=x_t-x_t-4, so delta_velocity = v_t+1-v_t), which is obviously different from your dtp_target file. Is my understanding correct?

**Comment by hunterace832100** [comment]
In other words, the content of dtp_target.npy is predicted by DTP, not calculated by the GT bounding box?

**Comment by olly-styles** [comment]
That's correct, but the change in velocity is always relative to the last observed timestep t, rather than the previous timestep. e.g. delta_veloctity_{t+20} = velocity_{t+20} - velocity_{t}

Hope that makes sense. This is explained in more detail in Section III-B of the DTP paper.

**Comment by hunterace832100** [comment]
Thank you for your answer

But I still can't get the dtp_target.npy file similar to yours through your method. I think the following methods obtained by the target file are all excluded, because the data in your target file is like this:
![图片](https://user-images.githubusercontent.com/61568829/98629822-ad7ff000-2354-11eb-9d8f-f26110eac359.png)

1. So this is obviously not the future bounding box value
2. After my calculations, this is not what you mentioned in the paper, the speed change value, and even I did not find where the output of the decoder mentioned in your paper is used.
![图片](https://user-images.githubusercontent.com/61568829/98629935-f6d03f80-2354-11eb-9620-bc081ab54ecf.png)

So I still wonder how your target file is calculated?

I am very grateful if I can get your answer.

**Comment by hunterace832100** [comment]
One more thing needs to be added, I used the method you mentioned in Section III-B of the DTP paper, that is, target.npy is the difference between the true bounding box and the Constant velocity (CV) bounding box. Use the GT bounding box and CV bounding box data you provided, but it is still much different from your target file.

**Comment by olly-styles** [comment]
I think the issue is with how the targets are reshaped. Notice how we reshape the target array [here](https://github.com/olly-styles/Multiple-Object-Forecasting/blob/625c1ffabe506c7e3d4567a5ee9a346b3c5a0f0a/metrics.py#L65)

Does reshaping the targets in this way give the result you were expecting?

**Comment by hunterace832100** [comment]
Thank you very much for your patient answer. 

But my question is actually, what exactly does your dtp_target.npy file represent? Is dtp_target.npy the difference between the true bounding box and the bounding box in the case of constant velocity?

**Comment by olly-styles** [comment]
Yes, that's right. `dtp_target.npy` is the difference between the ground truth bounding box and that of the bounding box predicted by the constant velocity baseline.

**Comment by hunterace832100** [comment]
Ok, thank you very much for your answer
