### ISSUE TITLE
Please tell me how to realize the visualization shown in Figure 6？Thank U

### ISSUE THREAD

**Issue by GodT998** [olly-styles/Multiple-Object-Forecasting#2]

**Comment by olly-styles** [comment]
Thanks for your interest in our work. We draw the bounding boxes and trajectories using Open-CV in Python. Specifically, we use the cv2.rectangle() for bounding boxes, cv2.line() for the trajectory, and cv2.addWeighted() to create the transparent coloured boxes. We're not releasing the visualization code, but you should be able to create the same visualization with a combination of these functions.

**Comment by GodT998** [comment]
I'm a rookie, so I don't know how to use Open-CV for programming. Can you share the source code of the visualization part with me? If you can, I will be very grateful. This is my email: 915052170@qq.com
