### ISSUE TITLE
Can you send the visualization code to my email: mo7ameda7med@live.com or the method of importing model to the visualization code 

### ISSUE THREAD

**Issue by MohamedHesham02** [olly-styles/Multiple-Object-Forecasting#20]

**Comment by olly-styles** [comment]
Thanks for your interest in our work. We draw the bounding boxes and trajectories using Open-CV in Python. Specifically, we use the cv2.rectangle() for bounding boxes, cv2.line() for the trajectory, and cv2.addWeighted() to create the transparent coloured boxes. We're not releasing the visualization code, but you should be able to create the same visualization with a combination of these functions.

**Comment by MohamedHesham02** [comment]
Yes sure, I think it's an easy part for me but the previous part like importing pytorch file in opencv and if there a classes which are defined in the model will be imported in opencv visualization code firstly before using cv.recantagle , I think this the problem for me.

**Comment by MohamedHesham02** [comment]
And also please in cv2.dnn.., what pretrained weight should be loaded rcnn or yolo, decoder or encoder and which folder 1, 2 or 3
I think also its confusing
