### ISSUE TITLE
I want to know the final returned values that should I represent from yolo and rcnn? 

### ISSUE THREAD

**Issue by MohamedHesham02** [olly-styles/Multiple-Object-Forecasting#21]
From the output csv file, What I understood that
Yolo and rcnn returns 2 bboxes of x1, x2, y1, y2 
, ground truth bboxe x1, x2, y1, y2
In addition to ADE, FDE, AIOU, FIOU 
Is there another returned values?

**Comment by olly-styles** [comment]
Details of the output CSVs are contained in the `Evaluating Multiple Object Forecasting models on Citywalks` section of the README. Metrics (ADE/FDE/AIOU/FIOU) are obtained by using `evaluate_outputs.py` with the ground truth and prediction CSVs, explained in the same section.
