### ISSUE TITLE
GPU memory

### ISSUE THREAD

**Issue by AmingWu** [olly-styles/Multiple-Object-Forecasting#3]
The work is very interesting. How long does your model need to train? How much GPU memory does your model need?

**Comment by olly-styles** [comment]
Glad to hear you're finding our work interesting. We trained STED on an NVIDIA GTX 1080TI. With pre-computed optical flow features, it requires around 2GB of VRAM and takes about 22 seconds per epoch. That's a total of 7-8 minutes of training time for 20 epochs. Computing the optical flow features is more time consuming, please see our DTP repo and paper (https://github.com/olly-styles/Dynamic-Trajectory-Predictor) for details on this.
