### ISSUE TITLE
How train the flownet?

### ISSUE THREAD

**Issue by xialulu826** [olly-styles/Multiple-Object-Forecasting#4]
hi,I have interest in your work.I wonder how you train the flownet,only use the  Open data set or add some your private data set.I look forward to your reply,thanks.

**Comment by olly-styles** [comment]
Hi, thanks for your interest in our work. We used the pre-trained FlowNet2 models from here: https://github.com/NVIDIA/flownet2-pytorch

The model is trained on a number of datasets. The FlowNet2 paper has details of this: https://arxiv.org/pdf/1612.01925.pdf
