### ISSUE TITLE
STED's runtime

### ISSUE THREAD

**Issue by Senwang98** [olly-styles/Multiple-Object-Forecasting#5]
Hi,
After reading your paper, i want to know the whole runtime of STED.

**Comment by olly-styles** [comment]
Hi,
We haven't measured the runtime precisely. However, in approximate terms: Computing the optical flow is the most computationally expensive step, followed by the optical flow encoder steam. The bounding box encoder and decoder runs quickly. The model should run at 30FPS on a good GPU with a fast optical flow estimation algorithm, but not with the algorithm we used (FlowNet2, which runs more slowly).
