### ISSUE TITLE
How to visualize the result?

### ISSUE THREAD

**Issue by albertchristian92** [olly-styles/Multiple-Object-Forecasting#6]
Hello, thank you for your good works. I tried your code and it works well, may i inquire how to visualize the result as showed in your video result? Thank you very much.

**Comment by olly-styles** [comment]
Thanks for your interest in our work. We draw the bounding boxes and trajectories using Open-CV in Python. Specifically, we use the cv2.rectangle() for bounding boxes, cv2.line() for the trajectory, and cv2.addWeighted() to create the transparent coloured boxes. We're not releasing the visualization code, but you should be able to create the same visualization with a combination of these functions.
