### ISSUE TITLE
How to train on my own dataset?

### ISSUE THREAD

**Issue by Senwang98** [olly-styles/Multiple-Object-Forecasting#7]
Hi,
Thanks for your  work, i feel confused about how to train on my own dataset. 
I think you use YoLo-v3 and DeepSort to get the bounding box features and save this features to a .csv file,  then use FlowNet2 to get optical flow(the whole picture or just detection area?),  the question is how to use my  flow result to train DTP features(based on your another github project, because i can't understand that project)?

**Comment by olly-styles** [comment]
Thanks for your interest in our work. We do indeed use YOLOv3 followed by DeepSort, and then FlowNet2 get optical flow from just the detection area. DTP uses a stack of the optical flow frames as input to a ResNet backbone to compute features. If your question is regarding DTP, could you open an issue on that repo instead? Thank you.

**Comment by Senwang98** [comment]
Thanks for your reply!
