### ISSUE TITLE
When and what to do with tracking result?

### ISSUE THREAD

**Issue by alexivaner** [olly-styles/Multiple-Object-Forecasting#8]
Hi, I am interested in your project, I would like to try to predict my own video using this Multiple Object Forecasting. I have a question, now I already could output tracking result from my own video using Yolo v4. I already make a program that generates the same csv with your format like this part of the explanation:
![image](https://user-images.githubusercontent.com/57290644/87946751-03463900-cad5-11ea-964d-530bfb08d47e.png)

I am sorry but where we would use this csv in case of this MOF. Really glad if you could explain more regarding this. Thank you very much.

**Comment by Senwang98** [comment]
Hi, alexivaner
I am trying to train this interesting project on my own dataset too. From my point of view, i think the author use DeepSort directly based on YoLo-v3. I am try to use this repo to meet MOF's need(**https://github.com/ZQPei/deep_sort_pytorch**), but my tracking result on Citywalks seems to be wrong. So, my option is that you use DeepSort based on YoLo, maybe there is no need to do detection first and then track.

**Comment by alexivaner** [comment]
@1187697147 Hi thank you for your reply, I used deepsort with Yolo-v4.[This link](https://github.com/LeonLok/Deep-SORT-YOLOv4) But in this repository there is no way to generate tracking result csv like the requirement from this part:
![image](https://user-images.githubusercontent.com/57290644/88039012-a2247100-cb79-11ea-9df5-eea44e5d2315.png)

Then I added somecode to generate csv for tracking result.  Now I already got my tracking result from my own videos in csv part, but how we put this tracking result to MOF? Because I see that evaluate_output.py don't really use this tracking result for evaluating? Is it possible to change citywalk video with our own video for this MOF? Thank you very much for your answer.

**Comment by Senwang98** [comment]
Hi, alex
I think evaluate_output.py is written to evaluate MOF's results rather than tracking results and tracking results are used to CNN(ResNet18), my option is that you can use deepsort and flownet2 to get pre-prepared optical flow dataset and save tracking csv at the same time. This is my own understanding and maybe wrong.

**Comment by alexivaner** [comment]
@1187697147 Hi thank you for your answer, I am sorry I wrongly type evaluate_output.py, it should be evaluate_sted.py. So we manually should use deepsort and flownet if we use our own video? Thank you

**Comment by Senwang98** [comment]
Hi, alex
My temporary plan is to preprocess the feature file like the author. I don’t know if you have read another paper and code (DTP) of the author. The author uses yolo to detect pedestrians, and then uses Flownet2 to calculate optical flow for the detection area, then use resnet18 to learn pred error. The input of the GRU part is only a subsidiary product of calculating the optical flow.

**Comment by olly-styles** [comment]
Hi both,

Glad to hear that you're interested in the project, I hope you will be able to generate results on your own dataset.

To generate results on your own dataset, you will need to detect and track objects first. I used this repo for that: https://github.com/Qidian213/deep_sort_yolov3

You will then need to compute optical flow from within the object bounding boxes. I used this repo: https://github.com/NVIDIA/flownet2-pytorch

It may be helpful to refer to my other paper and repo: https://github.com/olly-styles/Dynamic-Trajectory-Predictor
Paper: https://arxiv.org/pdf/1905.03681.pdf

STED is an extension of the DTP model introduced in that work.

**Comment by Senwang98** [comment]
Thank you very much for your reply!

**Comment by alexivaner** [comment]
@olly-styles Thank you, now I started to get some insight, I will try to read more about DTP. Your project and research really helps us a lot to study about pedestrian forecasting.

@1187697147 Thank you glad to have discussion with both of you.
